version: '3'
services:
  web:
    build: .
    container_name: readme
    ports:
      - "8083:8083"
    # Include volumes only if you have specific files or directories to persist
    volumes:
      - ./data:/usr/src/app/data
    restart: unless-stopped
